name: Deploy
 
on:
  push:
    branches:
      - master
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 17
          # node 版本控制
          cache: npm
          cache-dependency-path: '**/package-lock.json'
          # cache: yarn 如果用的yarn
      - name: Install
        run: 
          npm install
          # yarn install 安装依赖命令
      - name: Build
        run: 
          npm run build
          # yarn build 打包命令
      # - name: Git config email
      # 如果权限问题，可能是勾选不对，如果勾选对了，可以试试加上下面的配置。
      #   run:
      #     git config --global user.email "xxx@qq.com"
      # - name: Git config name
      #   run:
      #     git config --global user.name "xxx"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          # 打包文件的根目录，也就是提交到 gh-pages 分支的根目录

